version: '3.9'

services:
  database:
    container_name: postgres-db
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
