version: '3.9'

services:
  app:
    container_name: yellow-dolphin
    image: yellow-dolphin
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    env_file: .env
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database
  database:
    container_name: mongodb
    image: mongo
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - app-network
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

networks:
  app-network:

volumes:
  db:
